In [1]:
import pandas as pd
import numpy as np
pd = pd.read_csv('votes.csv', skipinitialspace = True)
pd

              a  b  c  d  e  f  g  h  i  j  k  l  m  n  o  p  q
0    republican  n  y  n  y  y  y  n  n  n  n  n  y  y  y  n  ?
1      democrat  ?  y  y  ?  y  y  n  n  n  n  y  n  y  y  n  n
2      democrat  n  y  y  n  ?  y  n  n  n  n  y  n  y  n  n  y
3      democrat  y  y  y  n  y  y  n  n  n  n  y  ?  y  y  y  y
4      democrat  n  y  y  n  y  y  n  n  n  n  n  n  y  y  y  y
..          ... .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..
429  republican  n  n  y  y  y  y  n  n  y  y  n  y  y  y  n  y
430    democrat  n  n  y  n  n  n  y  y  y  y  n  n  n  n  n  y
431  republican  n  ?  n  y  y  y  n  n  n  n  y  y  y  y  n  y
432  republican  n  n  n  y  y  y  ?  ?  ?  ?  n  y  y  y  n  y
433  republican  n  y  n  y  y  y  n  n  n  y  n  y  y  y  ?  n

[434 rows x 17 columns]

In [2]:
new_pd = pd.replace({'?': np.nan}).dropna()
new_pd

              a  b  c  d  e  f  g  h  i  j  k  l  m  n  o  p  q
4      democrat  n  y  y  n  y  y  n  n  n  n  n  n  y  y  y  y
7    republican  n  y  n  y  y  y  n  n  n  n  n  y  y  y  n  y
18     democrat  y  y  y  n  n  n  y  y  y  n  y  n  n  n  y  y
22     democrat  y  y  y  n  n  n  y  y  y  n  n  n  n  n  y  y
24     democrat  y  n  y  n  n  n  y  y  y  y  n  n  n  n  y  y
..          ... .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..
422    democrat  n  y  y  n  n  y  y  y  y  n  y  n  n  y  y  y
425    democrat  y  n  y  n  n  n  y  y  y  y  n  n  n  n  y  y
426  republican  n  n  n  y  y  y  y  y  n  y  n  y  y  y  n  y
429  republican  n  n  y  y  y  y  n  n  y  y  n  y  y  y  n  y
430    democrat  n  n  y  n  n  n  y  y  y  y  n  n  n  n  n  y

[232 rows x 17 columns]

In [3]:
new_pd = new_pd.replace({'democrat':0, 'republican': 1, 'n':0, 'y': 1})
new_pd

     a  b  c  d  e  f  g  h  i  j  k  l  m  n  o  p  q
4    0  0  1  1  0  1  1  0  0  0  0  0  0  1  1  1  1
7    1  0  1  0  1  1  1  0  0  0  0  0  1  1  1  0  1
18   0  1  1  1  0  0  0  1  1  1  0  1  0  0  0  1  1
22   0  1  1  1  0  0  0  1  1  1  0  0  0  0  0  1  1
24   0  1  0  1  0  0  0  1  1  1  1  0  0  0  0  1  1
..  .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..
422  0  0  1  1  0  0  1  1  1  1  0  1  0  0  1  1  1
425  0  1  0  1  0  0  0  1  1  1  1  0  0  0  0  1  1
426  1  0  0  0  1  1  1  1  1  0  1  0  1  1  1  0  1
429  1  0  0  1  1  1  1  0  0  1  1  0  1  1  1  0  1
430  0  0  0  1  0  0  0  1  1  1  1  0  0  0  0  0  1

[232 rows x 17 columns]

In [4]:
#parties is first column
parties = new_pd.iloc[:,0]
parties

4      0
7      1
18     0
22     0
24     0
      ..
422    0
425    0
426    1
429    1
430    0
Name: a, Length: 232, dtype: int64

In [5]:
#votes is the rest
votes = new_pd.iloc[:,1:16]
votes

     b  c  d  e  f  g  h  i  j  k  l  m  n  o  p
4    0  1  1  0  1  1  0  0  0  0  0  0  1  1  1
7    0  1  0  1  1  1  0  0  0  0  0  1  1  1  0
18   1  1  1  0  0  0  1  1  1  0  1  0  0  0  1
22   1  1  1  0  0  0  1  1  1  0  0  0  0  0  1
24   1  0  1  0  0  0  1  1  1  1  0  0  0  0  1
..  .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..
422  0  1  1  0  0  1  1  1  1  0  1  0  0  1  1
425  1  0  1  0  0  0  1  1  1  1  0  0  0  0  1
426  0  0  0  1  1  1  1  1  0  1  0  1  1  1  0
429  0  0  1  1  1  1  0  0  1  1  0  1  1  1  0
430  0  0  1  0  0  0  1  1  1  1  0  0  0  0  0

[232 rows x 15 columns]

In [6]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', max_iter=1000)
rfe = RFE(model, n_features_to_select=10) 
fit = rfe.fit(votes, parties)

In [7]:
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

Num Features: 10
Selected Features: [False False  True  True  True  True False False  True  True  True  True
 False  True  True]
Feature Ranking: [4 6 1 1 1 1 2 5 1 1 1 1 3 1 1]

In [8]:
#votes = votes[["d","e"]] #2 features
#votes = votes[["d","e","l"]] #3 features
#votes = votes[["d","e","f","l"]] #4 features
#votes = votes[["d","e","f","l","o"]] #5 features
#votes = votes[["d","e","f","k","l","m","o"]]#7 features
#votes = votes[["d","e","f","j","k","l","m","o"]]#8 features
votes = votes[["d","e","f","g","j","k","l","m","o","p"]] #10 features
votes

     d  e  f  g  j  k  l  m  o  p
4    1  0  1  1  0  0  0  0  1  1
7    0  1  1  1  0  0  0  1  1  0
18   1  0  0  0  1  0  1  0  0  1
22   1  0  0  0  1  0  0  0  0  1
24   1  0  0  0  1  1  0  0  0  1
..  .. .. .. .. .. .. .. .. .. ..
422  1  0  0  1  1  0  1  0  1  1
425  1  0  0  0  1  1  0  0  0  1
426  0  1  1  1  0  1  0  1  1  0
429  1  1  1  1  1  1  0  1  1  0
430  1  0  0  0  1  1  0  0  0  0

[232 rows x 10 columns]

In [9]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2, random_state=0).fit(votes)

In [10]:
parties_predict = kmeans.labels_
parties_predict

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0])

In [11]:
kmeans.n_iter_

3

In [12]:
kmeans.inertia_

291.31504608980055

In [13]:
from sklearn.metrics import accuracy_score
accuracy_score(parties, parties_predict)

0.9051724137931034